version: '3.8'

services:
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV:-development}
    ports:
      - "8000:8000"
    volumes:
      - ./server/fitness.db:/app/fitness.db
    environment:
      - PYTHONPATH=/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    ports:
      - "3000:3000"
    depends_on:
      - api