"""noramlization

Revision ID: 58e5a5e33f57
Revises: 0af5a50cb1a7
Create Date: 2025-05-18 11:58:29.690952

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "58e5a5e33f57"
down_revision: str | None = "0af5a50cb1a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "musclegroup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_musclegroup_id"), "musclegroup", ["id"], unique=False)
    op.create_index(op.f("ix_musclegroup_name"), "musclegroup", ["name"], unique=True)
    op.add_column("exercise", sa.Column("muscle_group_id", sa.Integer(), nullable=False))
    op.add_column("exercise", sa.Column("aliases", sa.JSON(), nullable=False))
    op.drop_index("ix_exercise_muscle_group", table_name="exercise")
    op.create_index(op.f("ix_exercise_aliases"), "exercise", ["aliases"], unique=False)
    op.create_index(op.f("ix_exercise_muscle_group_id"), "exercise", ["muscle_group_id"], unique=False)
    op.create_foreign_key(None, "exercise", "musclegroup", ["muscle_group_id"], ["id"])
    op.drop_column("exercise", "muscle_group")
    op.create_index(op.f("ix_training_date"), "training", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_training_date"), table_name="training")
    op.add_column("exercise", sa.Column("muscle_group", sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, "exercise", type_="foreignkey")
    op.drop_index(op.f("ix_exercise_muscle_group_id"), table_name="exercise")
    op.drop_index(op.f("ix_exercise_aliases"), table_name="exercise")
    op.create_index("ix_exercise_muscle_group", "exercise", ["muscle_group"], unique=False)
    op.drop_column("exercise", "aliases")
    op.drop_column("exercise", "muscle_group_id")
    op.drop_index(op.f("ix_musclegroup_name"), table_name="musclegroup")
    op.drop_index(op.f("ix_musclegroup_id"), table_name="musclegroup")
    op.drop_table("musclegroup")
    # ### end Alembic commands ###
