"""add_aliases

Revision ID: d3a6fa6b9077
Revises: 0af5a50cb1a7
Create Date: 2025-05-18 11:40:35.181844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a6fa6b9077'
down_revision: Union[str, None] = '0af5a50cb1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('aliases', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_exercise_aliases'), 'exercise', ['aliases'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_aliases'), table_name='exercise')
    op.drop_column('exercise', 'aliases')
    # ### end Alembic commands ### 